# fly.toml app configuration file generated for backend-vocational-test on 2023-07-02T18:47:29-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backend-vocational-test"
primary_region = "gig"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
